name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build RPM
      run: sudo apt-get install rpm && cargo install cargo-generate-rpm && make rpm
    - name: Archive RPM
      uses: actions/upload-artifact@v4
      with:
        name: reniced.x86_64.rpm
        path: target/generate-rpm/reniced-*.x86_64.rpm
